#!/usr/bin/env bash
#install Nginx on Server
apt-get update
apt-get install -y nginx

#run nginx
service nginx start

update-rc.d nginx defaults

echo "Hello World!" > /var/www/html/index.nginx-debian.html
