#!/usr/bin/env bash
#redirect to 301

sudo apt-get -y update
sudo apt-get -y install nginx

#run nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
echo "Hello World" | sudo tee /var/www/html/index

sudo sed -i '/server_name _;/a location = /redirect_me { return 301 https://www.youtube.com; }' /etc/nginx/sites-available/default

sudo service nginx restart
