#!/usr/bin/env bash
#redirect Nginx 301

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /etc/nginx/html/index.html

# Create a new configuration file for the redirect
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect

# Symlink to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Check configuration for syntax errors
sudo nginx -t

# If there were no errors, restart Nginx
sudo service nginx restart
