#!/usr/bin/env bash
#bash script to double the number of webservers
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/server {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
