#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration

count=1

while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
		count=$((count+1))
done
