#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20

i=1
while [[ $i -le 20 ]];
do
	case $i in
		4)
			echo "bad luck from China"
			;;
	case $i in
		9)
			echo "bad luck from Japan"
			;;
	case $i in
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
