#!/usr/bin/env bash
#Bash script that displays the content of the current directory

for file in *
do
	if [[ $file == -* ]] || [[ ! -f $file ]];
	then
		continue
	fi

	name=$(echo "$file" | cut -d '-' -f 2-)
	echo "$name"
done
