#!/usr/bin/env bash
#Bash script that gives you information about the school file

FILE_PATH="/path/to/school/file"
if [ -e "$FILE_PATH" ];
then
	echo "school file exists"
	if [ -s "$FILE_PATH" ];
	then
		echo "school file is not empty"
		if [ -f "$FILE_PATH" ];
		then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
