#!/usr/bin/env bash
#bash script that allows installs ufw and allows traffic on port 22, 443, 80

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
