#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements

sudo cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2   localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8   facebook.com" | sudo tee -a /etc/hosts > /dev/null
